# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: LukeWeaver.sshc
PackageVersion: 0.7.0
InstallerType: portable
Commands:
- sshc
ReleaseDate: 2026-10-05
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/W-Industries-Luke/sshc/releases/download/v0.7.0/sshc-windows-amd64.exe
  InstallerSha256: 8A01589B23AF5E97E44AE803BA4953C7FA2062DE0E6C04D8AF1D01FBF8BB0C53
- Architecture: arm64
  InstallerUrl: https://github.com/W-Industries-Luke/sshc/releases/download/v0.7.0/sshc-windows-arm64.exe
  InstallerSha256: E783DFA26F5B67DBBF66E7230B4A7AE39B1731921CBA57BDF93322528FA304E8
ManifestType: installer
ManifestVersion: 1.12.0
