# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: LukeWeaver.sshc
PackageVersion: 0.6.2
InstallerType: portable
Commands:
- sshc
ReleaseDate: 2026-10-05
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/W-Industries-Luke/sshc/releases/download/v0.6.2/sshc-windows-amd64.exe
  InstallerSha256: 97E26AE7C55D372DD084E92FFE3BA2E66A34897A62E38FE02993763383B4D1E4
- Architecture: arm64
  InstallerUrl: https://github.com/W-Industries-Luke/sshc/releases/download/v0.6.2/sshc-windows-arm64.exe
  InstallerSha256: 2E1318660B3EFF4989CC882EBFD98ABD5BCBFB1AFD4DD78D950D4AE6AE1F572B
ManifestType: installer
ManifestVersion: 1.12.0
